# Generated by Django 5.0.2 on 2024-04-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCarpool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(default='False', max_length=100)),
                ('end', models.CharField(default='False', max_length=100)),
                ('time', models.TimeField(null=True)),
                ('via', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('scooter', 'Scooter'), ('bike', 'Bike')], default='car', max_length=100)),
                ('max_seats', models.IntegerField(default=0)),
                ('no_of_seats', models.IntegerField(default=0)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product_delivery', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('delivery_price', models.IntegerField(blank=True, default='False', null=True)),
                ('music', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('ac', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('chitchat', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('pet', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('smoking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('eatdrink', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100)),
                ('paymentpic', models.FileField(upload_to='paymentpics/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='False', max_length=100)),
                ('name', models.CharField(default='False', max_length=100)),
                ('password', models.CharField(default='False', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('city', models.CharField(default='False', max_length=100)),
                ('phno', models.CharField(default='False', max_length=10)),
                ('occupation', models.CharField(default='False', max_length=100)),
                ('id_proof', models.FileField(null=True, upload_to='idproofs/')),
                ('driving_license', models.FileField(null=True, upload_to='drivinglicenses/')),
                ('profile_pic', models.FileField(null=True, upload_to='propics/')),
            ],
        ),
        migrations.CreateModel(
            name='JoinCarpool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(default='False', max_length=100)),
                ('end', models.CharField(default='False', max_length=100)),
                ('request', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('carpool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_carpool', to='MithraApp.createcarpool')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_carpool_user', to='MithraApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(default='False', max_length=100)),
                ('end', models.CharField(default='False', max_length=100)),
                ('pro_size', models.IntegerField(default=0)),
                ('pro_wgt', models.IntegerField(default=0)),
                ('pro_name', models.CharField(default=0, max_length=100)),
                ('pro_anyother', models.CharField(default='False', max_length=100)),
                ('request', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('carpool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_deliveries', to='MithraApp.createcarpool')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='MithraApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='createcarpool',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MithraApp.user'),
        ),
    ]
