# Generated by Django 3.2 on 2024-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcarpool',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
