# Generated by Django 3.2 on 2024-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0002_alter_createcarpool_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='carpool_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joincarpool',
            name='carpool_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joincarpool',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
