# Generated by Django 3.2 on 2024-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0003_auto_20240420_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
