# Generated by Django 3.2 on 2024-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0004_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcarpool',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='createcarpool',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
