# Generated by Django 3.2 on 2024-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0005_auto_20240420_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driving_license',
            field=models.FileField(null=True, upload_to='./frontend/drivinglicenses/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.FileField(null=True, upload_to='./frontend/idproofs/'),
        ),
    ]
