# Generated by Django 3.2 on 2024-04-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0006_auto_20240422_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcarpool',
            name='paymentpic',
            field=models.FileField(upload_to='./frontend/paymentpics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='./frontend/propics/'),
        ),
    ]
