# Generated by Django 3.2 on 2024-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0007_auto_20240423_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcarpool',
            name='paymentpic',
            field=models.FileField(upload_to='./frontend/images/paymentpics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license',
            field=models.FileField(null=True, upload_to='./frontend/images/drivinglicenses/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.FileField(null=True, upload_to='./frontend/images/idproofs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='./frontend/images/propics/'),
        ),
    ]
