# Generated by Django 5.0.3 on 2024-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0008_auto_20240423_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.FileField(null=True, upload_to='./frontend/imagesidproofs/'),
        ),
    ]
