# Generated by Django 5.0.3 on 2024-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0009_alter_user_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcarpool',
            name='search_route',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=200),
        ),
    ]
