# Generated by Django 5.0.3 on 2024-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0010_createcarpool_search_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
