# Generated by Django 3.2 on 2024-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0012_auto_20240429_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='r4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r5',
            field=models.IntegerField(default=0),
        ),
    ]
