# Generated by Django 3.2 on 2024-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0013_auto_20240429_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driverid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joincarpool',
            name='driverid',
            field=models.IntegerField(default=0),
        ),
    ]
