# Generated by Django 3.2 on 2024-04-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0014_auto_20240429_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='userid',
            new_name='passengerid',
        ),
        migrations.RenameField(
            model_name='joincarpool',
            old_name='userid',
            new_name='passengerid',
        ),
    ]
