# Generated by Django 3.2 on 2024-04-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0015_auto_20240429_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='pro_name',
            new_name='pro_type',
        ),
    ]
