# Generated by Django 3.2 on 2024-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0016_rename_pro_name_delivery_pro_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joincarpool',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
