# Generated by Django 5.0.3 on 2024-05-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithraApp', '0019_alter_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_verified',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
